---
# Title: "Coding lines to test Pearson’s product-moment correlations coefficient (rp) between root traits and correlogram visualisation in R language."
---

# loading files into the R environment, specifying the header is present, 
files located on desktop file 
Pearson_Dataset <- read.csv(
 file.choose(), 
 header=T
 ) 
 
# attach the data 
attach(Pearson_Dataset) 

# review Pearson_Dataset 
Pearson_Dataset 

# review variable names 
names(Pearson_Dataset) 

# loading packages, install first of not yet installed
library(Hmisc) 
library(corrplot) 

# correlations using rcorr() with p-values 
# X being selected columns in dataset
Mcor <- rcorr(as.matrix(
 Pearson_Dataset[,X]), 
 type=“pearson” 
 ) 
 
# flattenCorrMatrix - obtained from sthda.com website 
# cormat : matrix of the correlation coefficients 
# pmat : matrix of the correlation p-values 
flattenCorrMatrix <- function(cormat, pmat) { 
 ut <- upper.tri(cormat) 
 data.frame( 
 row = rownames(cormat)[row(cormat)[ut]], 
 column = rownames(cormat)[col(cormat)[ut]], 
 cor =(cormat)[ut], 
 p = pmat[ut] 
 ) 
} 

#table of R and p values 
flattenCorrMatrix(Mcor$r, Mcor$P) 

#printing the correlation matrix 
Mcor1 <- signif(Mcor$r, 2) 

#printing the p-values of the correlations 
Mcor2 <- signif(Mcor$P, 2) 
182

#visualisation of corrplot() and its modifications 
corrplot.mixed(Mcor1, 
 upper = "circle", order = "AOE", 
 lower = "number", p.mat = Mcor2, sig.level = 0.05
 )